### ISSUE TITLE
Adding pod for v5.11.3

### ISSUE THREAD

**Issue by split** [zoom-us-community/zoom-sdk-pods#12]
Currently latest pods have this [issue with App Store validation, that should be resolved in 5.11.3](https://devforum.zoom.us/t/v5-10-6-3611-causing-app-store-validation-issues/69823/13). It was released recently and would be awesome to add pod for it 🙂

Changelog entry https://8xmdmkir8ctlkfj8dttx.noticeable.news/publications/meeting-sdk-ios-v5-11-3-1220?embed=true

Thanks for providing these btw 💪

**Comment by zvs001** [comment]
@split  I added this version
```pod 'ZoomSDK', '5.11.3.4099'```

**Comment by zvs001** [comment]
@mieszko4 I checked lint function with this version. 
Now it works well with M1. Thank you
