### ISSUE TITLE
Update pod with version Zoom Meeting SDK - iOS - 5.15.3

### ISSUE THREAD

**Issue by VermontAlex** [zoom-us-community/zoom-sdk-pods#18]
Hello.

Could you please update pod to latest version [5.15.3](https://devsupport.zoom.us/hc/en-us/articles/17210683356173-Zoom-Meeting-SDK-iOS-5-15-3)?

**Comment by murtazakaz** [comment]
@mieszko4 any update on this 5.13.10.7064 pod? The Zoom SDK deadline is passed and the older version is not working anymore. 

`CocoaPods could not find compatible versions for pod "ZoomSDK":
  In Podfile:
    RNZoomUs (from `../node_modules/react-native-zoom-us`) was resolved to 6.17.0, which depends on
      ZoomSDK (= 5.13.10.7064)

None of your spec sources contain a spec satisfying the dependency: `ZoomSDK (= 5.13.10.7064)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.`

**Comment by mieszko4** [comment]
I am not sure what you mean. https://github.com/mieszko4/react-native-zoom-us-test works with `5.13.10.7064`.
And based on https://developers.zoom.us/docs/meeting-sdk/minimum-version/ it will be enforced after November 4, 2023

**Comment by murtazakaz** [comment]
@mieszko4 Hi, this issue react-native-zoom-us 6.18.0 gives this error where it's not finding available ZoomSDK 5.13.10.7064. I have checked the cocoa pods and there is no latest Zoom SDK version. The last version published on cocoapods is 5.11.3.4099.1 which is not working anymore. 

How to update react-native-zoom-us and use the latest Zoom SDK? help me

**Comment by mieszko4** [comment]
Not sure why you have an issue. Based on https://github.com/CocoaPods/Specs/blob/master/Specs/a/f/f/ZoomSDK/5.13.10.7064/ZoomSDK.podspec.json - the pod is there.

**Comment by murtazakaz** [comment]
@mieszko4 Yes I saw this but when I try to install react-native-zoom-us 6.18.0 or even 6.17.0 using zoomsdk pod 5.13.10.7064, getting same error. how to fix this?

`[!] CocoaPods could not find compatible versions for pod "ZoomSDK":
  In Podfile:
    RNZoomUs (from `../node_modules/react-native-zoom-us`) was resolved to 6.18.0, which depends on
      ZoomSDK (= 5.13.10.7064)

None of your spec sources contain a spec satisfying the dependency: `ZoomSDK (= 5.13.10.7064)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.`

**Comment by murtazakaz** [comment]
@mieszko4 I found the issue, need to upgrade the react native version to 0.70
Thanks :)
