### ISSUE TITLE
The 'Pods-App' target has framworks with conflicting names: mobilertc.framework

### ISSUE THREAD

**Issue by FrostyMint** [zoom-us-community/zoom-sdk-pods#2]
After i insert pod 'ZoomSDK', '5.4.54802.0124.1' the error message shown that the pods-app target has framworks with conflicting names: mobilertc.framework. Which i did try to delete whole ZoomSDK folder and pod install, it still does not work Please Help

**Comment by zvs001** [comment]
Did you have it in project before?
