### ISSUE TITLE
Merge 5.14.11.8690 and publish pod

### ISSUE THREAD

**Issue by frankie-fk** [zoom-us-community/zoom-sdk-pods#21]
My current project needs ZoomSDK 5.14.11.8690 for iOS.
Can we merge the project and publish the pod please? @mieszko4 @zvs001 ?

**Comment by frankie-fk** [comment]
For anyone who faces the same issue: I have published a pod named ZoomSDKPCOS: '5.14.11.8690', you can fork react-native-zoom-us and change the dependency in Podspec for yourself, this ZoomSDK fixes the issue for Zoom webinar on iOS.

**Comment by zvs001** [comment]
![image](https://github.com/zoom-us-community/zoom-sdk-pods/assets/25595191/b76627d7-b09c-4699-aac9-b245df6a401a)

**Comment by zvs001** [comment]
also added 2 newer versions: 
5.16.5.11131
5.15.12.10118
