### ISSUE TITLE
Upgrade zoom to v5.7.1.645

### ISSUE THREAD

**Issue by mieszko4** [zoom-us-community/zoom-sdk-pods#3]

**Comment by zvs001** [comment]
@mieszko4 I can add your email too for publishing. Send me which one I can use.

**Comment by mieszko4** [comment]
> @mieszko4 I can add your email too for publishing. Send me which one I can use.

Thnx, it is:
`mieszko4@gmail.com`

**Comment by zvs001** [comment]
@mieszko4 
done. List who can publish:

Owners:
    - Vlad Zaynchkovsky <zvsx001@gmail.com>
    - Miłosz Chmura <mieszko4@gmail.com>

**Comment by mieszko4** [comment]
Awesome, thnx, it's released now
