### ISSUE TITLE
New version v5.9.1.2191

### ISSUE THREAD

**Issue by pmogollons** [zoom-us-community/zoom-sdk-pods#6]
Hi @zvs001,

There is a new version of the iOS SDK that might help fix some issues in the react-native packages. Do you think you can update it or maybe I can make a PR and you can review and merge it?

https://marketplace.zoom.us/docs/changelog#publications/ios-meeting-sdk-v5-9-1-2191-patch

Thanks.

**Comment by zvs001** [comment]
You can try now.
`pod 'ZoomSDK', '5.9.1.2191'`

Please, let me know if you it works ok for you.

**Comment by pmogollons** [comment]
Its working, thanks.
