### ISSUE TITLE
Update to 5.9.6

### ISSUE THREAD

**Issue by pmogollons** [zoom-us-community/zoom-sdk-pods#7]
Hi @zvs001,

There is a new version of the iOS SDK, can you help by updating to the new SDK, please?

https://8xmdmkir8ctlkfj8dttx.noticeable.news/publications/ios-meeting-sdk-v5-9-6?embed=true

Thanks.

**Comment by zvs001** [comment]
Try:
```
pod 'ZoomSDK', '5.9.6.2769'
```

**Comment by pmogollons** [comment]
Thanks @zvs001
