### ISSUE TITLE
Has Zoom SDK added official support for pod?

### ISSUE THREAD

**Issue by mieszko4** [zoom-us-community/zoom-sdk-pods#9]
Based on https://8xmdmkir8ctlkfj8dttx.noticeable.news/publications/meeting-sdk-ios-v5-10-1 `Enhanced` section:
> Support for including SDK in a pod.

Has Zoom SDK for iOS added official support for pod? If yes, I guess this will make this repo obsolete.
However, I still cannot find that pod anywhere in https://cocoapods.org/.

**Comment by zvs001** [comment]
I think they never had official pod.
I always think why they will not create official pod for sdk.

Not sure what exactly means `Support for including SDK in a pod.`.
As you see pod worked for us and before.

They made `@zoom/react-native-videosdk` package. But by documentation they still link SDK manually.
So this repo still is very actual.

**Comment by mieszko4** [comment]
:rocket: I will close this :)
